# Generated by Django 5.1.3 on 2024-12-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Yearlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=30)),
                ('courses', models.ManyToManyField(related_name='year_levels', to='myapp.course')),
            ],
            options={
                'verbose_name': 'Year Level',
                'verbose_name_plural': 'Year Levels',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_unit', models.IntegerField(null=True)),
                ('section_time', models.CharField(default='TBA', max_length=200, null=True)),
                ('section_day', models.CharField(default='TBA', max_length=200, null=True)),
                ('section_room', models.CharField(default='TBA', max_length=200, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yearlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('school_year', models.CharField(blank=True, max_length=9, null=True)),
                ('enrollment_date', models.DateField(auto_now=True)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
                ('subjects', models.ManyToManyField(related_name='students', to='myapp.subject')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yearlevel')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yearlevel'),
        ),
    ]
