# Generated by Django 5.1.3 on 2024-12-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='lname',
            new_name='last_name',
        ),
    ]
