# Generated by Django 5.1.3 on 2024-12-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fname_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
