# Generated by Django 5.1.3 on 2024-12-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_instructor_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='contact_hours_laboratory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='contact_hours_lecture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_unit',
            field=models.IntegerField(null=True),
        ),
    ]
