# Generated by Django 5.1.3 on 2024-12-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_subject_contact_hours_laboratory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='semester_name',
        ),
    ]
