# Generated by Django 5.1.3 on 2024-12-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_semester_semester_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='instructors',
        ),
    ]
