# Generated by Django 5.1.3 on 2024-12-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_subject_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.section'),
        ),
    ]
