# Generated by Django 5.1.3 on 2024-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='section_day',
            field=models.CharField(default='TBA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='section_room',
            field=models.CharField(default='TBA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='section_time',
            field=models.CharField(default='TBA', max_length=200, null=True),
        ),
    ]
