# Generated by Django 5.1.3 on 2024-12-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_subject_section_day_alter_subject_section_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='No Address', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
