# Generated by Django 5.1.3 on 2024-12-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
    ]
