# Generated by Django 5.1.3 on 2024-12-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
    ]
