# Generated by Django 5.1.3 on 2024-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_student_cellphone_number_student_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], default='Regular', max_length=100),
        ),
    ]
