# Generated by Django 5.1.3 on 2024-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
